services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config:/opt/adguardhome/conf
      - ./data:/opt/adguardhome/work
    networks:
      - proxy

networks:
  proxy:
    external: true
